# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

workspace:
  clean: all

pool:
  name: 'Continuous Integration'
  demands: 
  - msbuild
  - visualstudio

steps:
  # Starter pipeline
- task: BuildSSIS@1
  inputs:
    solnPath: 'HimaUddaraju/TestingETL/Testing_SSIS_DevOps.sln'
    solnConfigName: 'SSIS_Solution_File'
    projPath: 'HimaUddaraju/TestingETL/tree/master/Testing_SSIS_Devops/Testing_SSIS_DevOps.dtproj'
    projConfigName: 'SSIS_Proj_File'
    cmdSwitch: 'build'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.ispac'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
